print("=======================================================")
name=str(input("Enter your Name:-"))
print()
id=int(input("Enter your Employee ID:-"))
print()
designation=str(input("Enter your Designation:-"))
print()
basic=int(input("Enter your Basic Pay:-"))
print()
print("""=======================================================
                 Employee Salary Slip
=======================================================
        """)
print("Employee Name:-",name)
print()
print("Employee ID:-",id)
print()
print("Employee Designation:-",designation)
print()
print("Employee Basic Pay:-",basic)
print()
print("=======================================================")
print()
print("Earnings                    Rate         Amount")
print()
print("Base Salary                              ",basic)
print()
hra=(0.10*basic)
print("House Rent Allowance         10%         " ,hra)
print()
ta=(0.05*basic)
print("Transportation Allowance     5%          " ,ta)
print()
print("=======================================================")
print()
gross=(hra+ta+basic)
print("Gross Salary                             " ,gross)
print()
print("=======================================================")
print()
ptax=(0.02*gross)
print("Professional Tax                         ",ptax)
print()
print("=======================================================")
print()
net=(gross-ptax)
print("Net Payable Salary                       ",net)
print()
print("=======================================================")