filename=input('Enter input filename:-')
file=open(filename,'r')
filedata=file.read()
file.close()
filedata=filedata.replace('.',',')
filedata=filedata.swapcase()
outputfilename=input('Enter output.txt filename:-')
file=open(outputfilename,'w')
file.write(filedata)
file.close()